import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SidebarProvider} from "@/components/ui/sidebar";
import { AppSidebar } from "./(routes)/(root)/components/AppSidebar";


const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${spaceGrotesk.variable} antialiased`}>
            <SidebarProvider>
            <AppSidebar />
              <main className="flex-1"></main>
            </SidebarProvider>
            </body>
      </html> 
      {children}
    </ClerkProvider>
  );
}
