import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SidebarProvider} from "@/components/ui/sidebar";
import { AppSidebar } from "./(routes)/(root)/components/AppSidebar";
import { Navbar, Footer } from "@/components/Shared";
import {Toaster} from "@/components/ui/sonner";


const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${spaceGrotesk.className} antialiased`}>
            <SidebarProvider>
            <AppSidebar />
            <div className="w-full bg-stone-100 flex flex-col min-h-screen">
              <Navbar />
            
              <main className="flex-1">{children}</main>
              
              <Toaster>
                
              </Toaster>

            <Footer />
            </div>
            </SidebarProvider>
            </body>
      </html> 
    </ClerkProvider>
  );
}
